---
title: "Untitled"
author: "Sophie Paul"
date: "11/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
numbers <- seq(1, 5)
numbers

mean(sqrt(numbers))
```

```{r}
numbers %>% sqrt() %>% mean()
```

```{r}
fastqc_data <- read_csv("data/fastqc_data.csv")
```

```{r}
summary(fastqc_data)
glimpse(fastqc_data)
head(fastqc_data)
```

```{r}
metadata <- read_csv("data/metadata.csv")
head(metadata)
```

```{r}
dataset <- left_join(fastqc_data, metadata, by = c("filename" = "file_name")) %>% unique()

dataset
```

```{r}
data_2 <- dataset %>%
  separate(filename, sep = "_", into = c("sample_name", "sample_number", "lane", "read", "something_else"))

data_2
```

```{r}
data_3 <- data_2 %>%
  extract(col = project_name, into = c("project_type", "run_name", "assay"), regex = "(\\d{3})_(.*)_(\\w+)$")

data_3
```

```{r}
data_4 <- data_3 %>%
  mutate(cycle = ifelse(read == "R1", Base, Base + 151))

data_4
```

```{r}
data_5 <- data_4 %>%
  select(starts_with("sample"), starts_with("project"), assay, run_name, lane, read, Base, cycle, everything())

data_5
```

```{r}
nrow(data_5) - nrow(fastqc_data)
```

```{r}
data_5 %>%
  filter(sample_name == "NA12878--TWE-0-EGG4")
```

```{r}
data_5 %>%
  group_by(sample_name, sample_number, lane, read, Base, something_else, Mean) %>%
  mutate(count = n()) %>%
  filter(count >= 2) %>%
  select(sample_name, Base, Mean, file_id, everything())
```

```{r}
data_6 <- data_5 %>%
  select(-file_id) %>%
  unique()
```

```{r}
nrow(data_6) - nrow(fastqc_data)
```

```{r}
theme_set(theme_bw())

ggplot(data = data_6, mapping = aes(x = cycle, y = Mean, group = paste0(sample_name, run_name, lane))) +
  geom_line(stat = "identity", aes(colour = run_name), alpha = 0.7)
```

```{r}
cycleplot <- ggplot(data = data_6, aes(x = cycle, y = Mean, group = paste0(run_name, lane))) +
  stat_summary(geom = "errorbar", fun = mean, fun.min = min, fun.max = max, aes(colour = run_name), alpha = 0.15) +
  stat_summary(geom = "line", fun = mean, aes(colour = run_name))

cycleplot


```

```{r}
cycleplot + 
  facet_wrap(~ lane) +
  ylab("Mean Q30") +
  geom_hline(colour = "red", yintercept = 30)
```

```{r}
data_6 %>%
  filter(cycle >= 292) %>%
  group_by(sample_name, run_name, lane) %>%
  summarise(m = mean(Mean)) %>%
  ungroup() %>%
  ggplot(aes(x = m)) +
    geom_density(aes(colour = run_name, fill = run_name, group = paste0(run_name, lane)), alpha = 0.5) +
  facet_grid(lane ~ .)
```
